### ISSUE TITLE
Please plan a migration path away from PHP_Crypt

### ISSUE THREAD

**Issue by paragonie-scott** [verdel/teampass#1]
https://github.com/gilfether/phpcrypt/issues/6

**Comment by verdel** [comment]
Hello.This repository was clone fork https://github.com/nilsteampassnet/TeamPass. Only reason for it was small amount of bug fix related to my work environment. From time to time I update source code from main developer repository.So if you want to use TeamPass, you must use https://github.com/nilsteampassnet/TeamPass repo.

**Comment by paragonie-scott** [comment]
Okay. Github didn't associate it as a fork, so I just imagined it was a name collision.

**Comment by verdel** [comment]
Excuse me for this confusion. I will change description of this repository. Thank you for this note.

**Comment by paragonie-scott** [comment]
Any time. I'm just trying to stop a bad crypto implementation from becoming a catastrophe. :)
